# Generated by Django 3.1.7 on 2021-05-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tovara', models.IntegerField(default=0)),
                ('id_postav', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('kol_vo', models.IntegerField(default=0)),
                ('cena', models.IntegerField(default=0)),
            ],
        ),
    ]
